version: '3.8'

services:
  reactcrud:
    image: reactcrud
    build:
      context: .
      dockerfile: BookStore.API/Dockerfile
    ports:
      - "3000:8080"
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
