# This is a generated file. Not intended for manual editing.
version: "3.8"
services:
  reactcrud:
    build:
      context: "D:\\Универ. Проекты\\RiderProjects\\ReactTestApp\\ReactCRUD"
      dockerfile: "BookStore.API/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/BookStore.API.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "reactcrud:dev"
    ports: []
    volumes:
    - "C:\\Users\\novik\\.nuget\\packages:/root/.nuget/packages"
    - "D:\\Универ. Проекты\\RiderProjects\\ReactTestApp\\ReactCRUD\\BookStore.API:/app:rw"
    - "D:\\Универ. Проекты\\RiderProjects\\ReactTestApp\\ReactCRUD:/src:rw"
    working_dir: "/app"
